[package]
name = "bd2wg-cli"
version = "1.0.0"
author.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bd2wg = { path = "../bd2wg", features = ["default_header"] }
anyhow.workspace = true
indicatif = "0.18"
